name: implicit-env
channels:
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - absl-py=1.0.0
  - blas=1.0
  - blosc=1.21.0
  - brotli=1.0.9
  - brunsli=0.1
  - bzip2=1.0.8
  - c-ares=1.18.1
  - ca-certificates=2021.10.8
  - certifi=2021.10.8
  - cfitsio=3.470
  - charls=2.2.0
  - cloudpickle=2.0.0
  - cycler=0.11.0
  - cytoolz=0.11.0
  - dask-core=2021.10.0
  - dbus=1.13.18
  - expat=2.4.1
  - fontconfig=2.13.1
  - fonttools=4.25.0
  - freetype=2.11.0
  - fsspec=2022.1.0
  - giflib=5.2.1
  - glib=2.69.1
  - gst-plugins-base=1.14.0
  - gstreamer=1.14.0
  - icu=58.2
  - igl=2.2.1
  - imagecodecs=2021.8.26
  - imageio=2.9.0
  - intel-openmp=2021.4.0
  - jax=0.2.27
  - jaxlib=0.1.75
  - jpeg=9d
  - jxrlib=1.1
  - kiwisolver=1.3.1
  - krb5=1.19.2
  - lcms2=2.12
  - ld_impl_linux-64=2.35.1
  - lerc=3.0
  - libaec=1.0.4
  - libblas=3.9.0
  - libcblas=3.9.0
  - libcurl=7.80.0
  - libdeflate=1.8
  - libedit=3.1.20210910
  - libev=4.33
  - libffi=3.3
  - libgcc-ng=11.2.0
  - libgfortran-ng=7.5.0
  - libgfortran4=7.5.0
  - libnghttp2=1.46.0
  - libpng=1.6.37
  - libssh2=1.9.0
  - libstdcxx-ng=11.2.0
  - libtiff=4.2.0
  - libuuid=1.0.3
  - libwebp=1.2.0
  - libwebp-base=1.2.0
  - libxcb=1.14
  - libxml2=2.9.12
  - libzopfli=1.0.3
  - llvm-openmp=12.0.1
  - locket=0.2.1
  - lz4-c=1.9.3
  - matplotlib=3.5.0
  - matplotlib-base=3.5.0
  - mkl=2021.4.0
  - mkl-service=2.4.0
  - mkl_fft=1.3.1
  - mkl_random=1.2.2
  - munkres=1.1.4
  - ncurses=6.3
  - networkx=2.6.3
  - numpy=1.21.2
  - numpy-base=1.21.2
  - olefile=0.46
  - openjpeg=2.4.0
  - openssl=1.1.1l
  - opt_einsum=3.3.0
  - packaging=21.3
  - partd=1.2.0
  - pcre=8.45
  - pillow=8.4.0
  - pip=21.2.4
  - polyscope=1.3.0
  - pyparsing=3.0.4
  - pyqt=5.9.2
  - python=3.9.7
  - python-dateutil=2.8.2
  - python-flatbuffers=2.0
  - python_abi=3.9
  - pywavelets=1.1.1
  - pyyaml=6.0
  - qt=5.9.7
  - readline=8.1.2
  - scikit-image=0.18.3
  - scipy=1.7.3
  - setuptools=58.0.4
  - sip=4.19.13
  - six=1.16.0
  - snappy=1.1.8
  - sqlite=3.37.0
  - tifffile=2021.7.2
  - tk=8.6.11
  - toolz=0.11.2
  - tornado=6.1
  - typing_extensions=4.0.1
  - tzdata=2021e
  - wheel=0.37.1
  - xorg-kbproto=1.0.7
  - xorg-libx11=1.7.2
  - xorg-libxext=1.3.4
  - xorg-libxinerama=1.1.4
  - xorg-xextproto=7.3.0
  - xorg-xproto=7.0.31
  - xz=5.2.5
  - yaml=0.2.5
  - zfp=0.5.5
  - zlib=1.2.11
  - zstd=1.4.9
